#!/bin/bash
cd /Users/harbertt11/_The\ University\ of\ Akron/FALL\ 2015/Senior\ Design\ Trunk/Image\ Correction/bin
cmake /Users/harbertt11/_The\ University\ of\ Akron/FALL\ 2015/Senior\ Design\ Trunk/Image\ Correction
make